### PR TITLE
Fix delete command giving wrong error message 

### LINKED ISSUE #248: [PE-D][Tester E] Large index values (e.g., 10000000000) show wrong error message in delete command
Image

The User Guide states that index values larger than the list size should give the error message "The order index provided is invalid". However, very large numbers (likely causing integer overflow) are being rejected with "Invalid command format!" instead of being validated as out-of-range indices. While such a number is unlikely to be reached with homechefs, it is still possible in the case of order history not being regularly cleared over time. 

Steps to reproduce:
1. Startup homechef with default order database loaded in
2. Use command "delete 10000000000"

Expected output:
The order index provided is invalid

Actual output:
Invalid command format! 
delete: Deletes the order identified by the index number used in the displayed order list.
Parameters: INDEX (must be a non-zero positive integer)
Example: delete 1

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by shanselvan**
Fixes #248 

Added additional check for overflow integers to ensure the correct error message is shown.

### CODE REVIEW

File: src/main/java/seedu/homechef/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -64,6 +64,9 @@ public static String normalizeWhitespace(String input) {
     public static Index parseIndex(String oneBasedIndex) throws ParseException {
         String trimmedIndex = normalizeWhitespace(oneBasedIndex);
         if (!StringUtil.isNonZeroUnsignedInteger(trimmedIndex)) {
+            if (trimmedIndex.matches("[1-9][0-9]*")) {
```
Comment (Omgeta) [inline src/main/java/seedu/homechef/logic/parser/ParserUtil.java:71]: Wouldn't this lead to an edge case where the if the order list really does have MAX_VALUE orders, then the out-of-bounds index automatically resolves to the final order list item instead of throwing an error? If the PE reviewers use AI to do a broad bug/edge-case check, then this edge-case could be brought up

**Review by Omgeta — CHANGES_REQUESTED** [review]
I think some some consideration is needed for a more robust solution

File: src/main/java/seedu/homechef/logic/parser/ParserUtil.java (hunk 1 above)
Comment (shanselvan) [reply src/main/java/seedu/homechef/logic/parser/ParserUtil.java:71]: I think the best solution would be to add a new subclass of ParseException like OversizedIndexException, which is thrown in the `parseIndex` method for overflowing integers:

```
String trimmedIndex = normalizeWhitespace(oneBasedIndex);
if (!StringUtil.isNonZeroUnsignedInteger(trimmedIndex)) {
    if (trimmedIndex.matches("[1-9][0-9]*")) {
        throw new OversizedIndexException(MESSAGE_INDEX_TOO_LARGE);
    }
    throw new ParseException(MESSAGE_INVALID_INDEX);
}
```

The exception will be caught in each of the respective *CommandParser class, for e.g:

```
public DeleteCommand parse(String args) throws ParseException {
        try {
            Index index = ParserUtil.parseIndex(args);
            return new DeleteCommand(index);
        // new catch block
        } catch (OversizedIndexException ie) {
            throw ie;
        } catch (ParseException pe) {
            throw new ParseException(
                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE), pe);
        }
    }
```

But problem is this would be too many new lines of functional code.

Another potential solution is to specify this behaviour in the docs i.e that overflowing integers are automatically set as `MAX_VALUE`. 

Or should I try something else what do you think?

Comment (Omgeta) [reply src/main/java/seedu/homechef/logic/parser/ParserUtil.java:71]: You could try doing the initial parse as a BigInteger so that it can store any sized integer without overflow. Then comparing to the range of acceptable indexes in the order/menu list would let you know if the parsedIndex is out-of-bounds so you can emit the correct error message

Comment (Omgeta) [reply src/main/java/seedu/homechef/logic/parser/ParserUtil.java:71]: I believe this would require atmost a few changes to the existing code, and/or StringUtil

Comment (Omgeta) [reply src/main/java/seedu/homechef/logic/parser/ParserUtil.java:71]: Actually, your current logic to check for overflow is probably fine, you can just throw a parseexception with a different message, then print it out in the calling method

**Review by Omgeta — DISMISSED** [review]
Approving because this technically does work, but it might get flagged for code quality and hurt your mark

**Comment by shanselvan** [comment]
Okay will update this soon

**Review by Omgeta — DISMISSED** [review]
LGTM

**Review by Omgeta — APPROVED** [review]
LGTM
