### PR TITLE
Fix Javadoc errors and add missing Javadoc on public members

### LINKED ISSUE #316: Add missing Javadoc and fix incorrect documentation across codebase

### PR DESCRIPTION
**Pull request by JoshTKx**
Fixes #316

### CODE REVIEW

File: src/main/java/seedu/homechef/model/order/BankPayment.java [hunk 1]
```diff
@@ -36,16 +36,25 @@ public static boolean isValidBankPayment(String test) {
         return VALID_REFERENCE.matcher(test).matches();
     }
 
+    /**
+     * Returns the bank transfer reference.
```
Comment (Yixiannya) [inline src/main/java/seedu/homechef/model/order/BankPayment.java:40]: Do we need Javadoc comments for override methods?

**Review by Yixiannya — DISMISSED** [review]
LGTM, though I think the Javadoc comments for override methods is unnecessary

File: src/main/java/seedu/homechef/model/order/BankPayment.java (hunk 1 above)
Comment (Omgeta) [reply src/main/java/seedu/homechef/model/order/BankPayment.java:40]: No, we don't

**Review by Omgeta — CHANGES_REQUESTED** [review]
You MUST write header comments for all classes, public methods. But they can be omitted for the following cases:
i. Getters/setters
ii. When overriding methods (provided the parent method's Javadoc applies exactly as is to the overridden method)
iii. In classes/methods used for testing

Image

Note in particular:

The opening /** on a separate line.
Write the first sentence as a short summary of the method, as Javadoc automatically places it in the method summary table (and index).
In method header comments, the first sentence should start in the form Returns ..., Sends ..., Adds ... etc. (not Return or Returning etc.)
Subsequent * is aligned with the first one.
Space after each *.
Empty line between description and parameter section.
Punctuation behind each parameter description.
No blank line between the documentation block and the method/class.
@return can be omitted if the method does not return anything or the return value is obvious from the rest of the comment.
@params can be omitted if all parameters of a method have self-explanatory names, or they are already explained in the main part of the comment i.e., if none of the @params add any value. This means the comment will have @param for all its parameters, or none.
When writing Javadocs for overridden methods, the @inheritDoc tag can be used to reuse the header comment from the parent method but with further modifications e.g., when the method has a slightly different behavior from the parent method.

Image

**Review by Omgeta — DISMISSED** [review]
LGTM

**Review by Omgeta — APPROVED** [review]
LGTM
