### PR TITLE
Fix command-related UG bugs

### LINKED ISSUE #233: [PE-D][Tester A] Users able to edit menu food even if it is in use by orders
Steps to reproduce:
1. Add a menu item: add-menu f/Burger $/5.00
2. Add an order referencing it: add f/Burger c/Test p/12345678 e/test@example.com a/123 Street d/10-04-2026
3. Edit the menu item's name: edit-menu INDEX f/Cheeseburger
4. View existing order: list

Expected behaviour:
Existing order that referenced "Burger" should either be updated to reflect "Cheeseburger", or the user should be warned/prevented from renaming a menu item that is currently in use by existing orders.

Actual behaviour:
The edit-menu command is successful. However, existing order still display the old food name "Burger", creating an inconsistency between the menu and the order records.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #246: [PE-D][Tester C] Exiting app with additional inputs
**Description:**

Currently, users are able to exit the application by typing `exit` followed by additional inputs. This can result in unintentional quitting the application. 

**Steps to reproduce:**
1. Execute `exit delete 23`

**Excepted:**
- Users should be prohibited from exiting the application.
- Should return an error message indicating invalid command format.

**Actual:**
- The application terminates and closes.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #250: [PE-D][Tester C] Incorrect link for `MainWindow` and `MainWindow.fxml` in developer guide
**Description:**

Currently, both the `MainWindow` and `MainWindow.fxml` are still pointing to AB3.

Image<br>

**Steps to reproduce:**
1. Click on the `MainWindow` in developer guide.
2. Click on the `MainWindow.fxml` in developer guide.

**Expected:**
- Both links should direct to `AY2526S2-CS2103T-T13-4` code.

**Actual:**
- Both links direct to `se-edu/addressbook-level3` code.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #263: [PE-D][Tester D] App allows generating a receipt for unpaid orders
### Description
The app allows generating an "Order Receipt" for orders that have a Payment Status of "Unpaid". In real-world usage, a receipt is a document that serves as proof of payment. Generating a receipt for an unpaid order is misleading and contradictory — the generated receipt itself shows "Payment Status: Unpaid", which defeats the purpose of a receipt. This could cause confusion for both the bakery staff and customers, as the document implies payment has been made when it has not.

---
### Steps to Reproduce
1. Launch the app using the jar file
2. Create or find an order that has Payment Status as "Unpaid"
3. Generate a receipt for that order
4. Observe that the receipt is generated successfully despite the order being unpaid

---
### Screenshots
1. The generated receipt showing "Payment Status: Unpaid"

Image

---
### Expected Behavior
The app should either prevent receipt generation for unpaid orders with an appropriate message (e.g., "Cannot generate receipt: order has not been paid"), or label the document as an "Invoice" or "Order Summary" instead of "Order Receipt".

---
### Actual Behavior
The app generates a full "Order Receipt" for an unpaid order, displaying "Payment Status: Unpaid" on the receipt itself.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #264: [PE-D][Tester D] `clear` command deletes all orders without requiring confirmation and has no undo feature
### Description
The `clear` command deletes all orders immediately without any confirmation prompt. Additionally, there is no undo feature to recover the deleted data. This makes the command extremely dangerous, as a single accidental invocation could result in permanent and irreversible data loss. In real-world usage, a bakery could have hundreds of orders in the system. A single accidental `clear` command would wipe all of them permanently with no way to recover. Destructive operations like this should either require a double confirmation (e.g., "Are you sure you want to delete all orders? Type 'yes' to confirm.") or provide an undo mechanism, ideally both.

---
### Steps to Reproduce
1. Launch the app using the jar file
2. Ensure there are existing orders in the system
3. Enter the `clear` command
4. Observe that all orders are immediately deleted without any confirmation
5. Attempt to undo the action — no undo feature is available

---
### Screenshots
1. The result after running `clear`, showing all orders wiped with no confirmation step.
Image

---
### Expected Behavior
The app should prompt the user for confirmation before executing the `clear` command (e.g., "This will delete all orders. Are you sure? Type 'yes' to confirm."), and/or provide an undo feature to recover accidentally deleted data.

---
### Actual Behavior
All orders are deleted immediately with no confirmation prompt and no way to undo or recover the data.
 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #266: [PE-D][Tester D] `clear` command displays incorrect success message "Address book has been cleared!"
### Description
After executing the `clear` command, the app displays the message "Address book has been cleared!" — however, this is not an address book application, it is a bakery order management system. The message appears to be a leftover from the original AB3 (AddressBook Level 3) codebase that was not updated to reflect the current product. This is misleading and hurts the product's credibility, as it suggests the app was not thoroughly adapted from its base project.

---
### Steps to Reproduce
1. Launch the app using the jar file
2. Enter the `clear` command
3. Observe the success message

---
### Screenshots
1. The success message showing "Address book has been cleared!"
Image

---
### Expected Behavior
The success message should reflect the actual product, e.g., "All orders have been cleared!" or "All data has been cleared!".

---
### Actual Behavior
The app displays "Address book has been cleared!" which references the wrong product.
 

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #278: [PE-D][Tester B] No handling of invalid paynow numbers
Description
Phone numbers require a minimum length of 3 digits and accept only numeric characters. However, PayNow numbers may contain letters and can be shorter than 3 characters. This inconsistency in validation rules may lead to confusion.

Image

Image

Steps to Reproduce

1. Launch the application.
2. Attempt to enter a PayNow number with fewer than 3 characters or containing letters. (i.e. O)

Expected Result

Validation rules for phone numbers and PayNow numbers should be consistent, or differences should be clearly justified and documented.

Actual Result

Phone numbers enforce stricter validation (numeric only, minimum 3 digits), while PayNow numbers allow more flexible input (letters and shorter length).

Additional Notes and Suggestions

Consider aligning validation rules or clarifying the distinction in the User Guide to avoid user confusion.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #292: [PE-D][Tester B] DG UI Class Diagram contains StatusBarFooter, which is not present in MainWindow
Image

The UI Class Diagram above shows that MainWindow contains a StatusBarFooter. However, the current implementation of MainWindow does not create, initialize, or display a StatusBarFooter.

Image

Above shows that the status bar footer seen in the AB3 address book is missing.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by serny-afk**
Fixes #233
Fixes #246
Fixes #250 
Fixes #263 
Fixes #264
Fixes #266 
Fixes #278 
Fixes #292

### CODE REVIEW

File: src/main/java/seedu/homechef/logic/commands/ClearCommand.java [hunk 1]
```diff
@@ -11,7 +11,7 @@
 public class ClearCommand extends Command {
 
     public static final String COMMAND_WORD = "clear";
-    public static final String MESSAGE_SUCCESS = "Address book has been cleared!";
+    public static final String MESSAGE_SUCCESS = "Order management system has been cleared!";
```
Comment (Omgeta) [inline src/main/java/seedu/homechef/logic/commands/ClearCommand.java]: It would be better if this made specific reference to HomeChef helper Orders
e.g. HomeChef Orders have been cleared!

**Review by Omgeta — CHANGES_REQUESTED** [review]
Only small change needed to the clear message

**Comment by Omgeta** [comment]
You should put the fixes on multiple lines so that it links correctly. Otherwise, only the first issue is linked

For example:
Fixes ...
Fixes ...
etc.

**Review by Omgeta — CHANGES_REQUESTED** [review]
The exact restriction for PayNow payments should be justified (maybe with a link) so that we can better justify the lack of restriction

For example here: https://www.dbs.com.sg/personal/deposits/pay-with-ease/paynow

It lists all the different reference options

**Review by Omgeta — APPROVED** [review]
LGTM
